### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by EcksDy** [themetalfleece/neogma#101]
Heya,
I've tried neogma today following the examples on README and docs, and couldn't get it to work.
For example `await Users.createOne({...})` from the example wont accept the object as first param:
```ts
Argument of type '{ id: string; name: string; age: number; }' is not assignable to parameter of type 'CreateDataI<Neo4jSupportedProperties, Object>'.
  Types of property 'constructor' are incompatible.
    Type 'Function' has no properties in common with type 'RelationshipTypePropertyForCreateI<unknown, unknown>'.ts(2345)
```
Main page also suggest `neogma.getDriver().close()` which doesnt exist anymore.
I couldn't find any working code in the docs to get started, but it seems that the repo is active, am I missing something?

**Comment by themetalfleece** [comment]
Hey there,

I'm a bit busy these days, but reading the error message maybe you haven't defined the appropriate types?
Following the docs, you are following the `Typescript` tab, right?

![image](https://github.com/user-attachments/assets/a8d9c1eb-3daf-420d-98bc-df5f782f0dae)

Thanks about the `close` note, I'll take a look.

**Comment by EcksDy** [comment]
Ahh I see, I was missing the generics setup, makes sense.
I was on the javascript tab, had a feeling I'm missing something :)

**Comment by themetalfleece** [comment]
Yeah this isn't the first time it happens. I should put the Typescript tab first!
