### ISSUE TITLE
Can not related to self model

### ISSUE THREAD

**Issue by tears330** [themetalfleece/neogma#14]
https://github.com/themetalfleece/neogma/blob/0e88975e9dc8aee77ef5925a5769551427c15d74/src/ModelOps/ModelOps.ts#L1386

Here is my model relationships define:
 ```ts
{
      ExtensionVersions: {
        model: ExtensionVersions,
        direction: 'out',
        name: RelationType.USE,
      },
      NextModuleVersions: {
        model: 'self',
        direction: 'out',
        name: RelationType.NEXT,
      },
}
```
`getLabel()` will the fail when the model is `self`

**Comment by themetalfleece** [comment]
Thanks for reporting this bug while providing details.
A typing issue was causing `relationship.model` to be of type `any`.
Also, the same issue was fixed in the `updateRelationship` static. A unit test was also added.

It's now deployed in `1.8.4`!
