### ISSUE TITLE
model.hasRelationship

### ISSUE THREAD

**Issue by tejo-ak** [themetalfleece/neogma#18]
Hello,
I need to check if a model had a certain relationship to another, like, a lot. It would be handy to add a function, for example: 'hasRelationship' to the model's instance:

`user.hasRelationship({alias:'LikesMovie', where:{id:movie.id}});`

As you noticed, this is based on the `relateTo(...)` pattern, which I like and use a lot. 

Thanks for considering.

p.s.
This lib works so well for me. won't get enough to appreciate your work!.

**Comment by themetalfleece** [comment]
I'm glad that you like Neogma, and that it suits you well!
Thanks for submitting this, it's another great improvement! I'll implement it when I find some time in the following weeks.

**Comment by themetalfleece** [comment]
@tejo-ak I'm considering the following, which has more uses:

```ts
const relationships = await user.getRelationships({
    alias: 'LikesMovie',
    targetWhere: { id: movie.id },
    limit: 1,
    relationshipWhere: { since: 2021 }
});

console.log(relationships[0].target.name); // "John Wick"
console.log(relationships[0].relationship.since); // 2021
console.log(!!relationships.length); // true
```
All params except for `alias` are optional.
Using `limit`, you can improve its performance if you just want to see if the relationship just exists.

Do you think it's simple enough for your case, or should I create a dedicated `hasRelationship` method?

**Comment by tejo-ak** [comment]
Hello,
Yes, this approach works in my use thanks.

In which version will this api available?

Thanks again.

**Comment by themetalfleece** [comment]
I ended up adding a `findRelationships` Model static (and an Instance method as a wrapper).
[Docs](https://themetalfleece.github.io/neogma-docs/docs/Models/Finding-Nodes-And-Relationships#finding-nodes-and-relationships-via-the-model-static).
Deployed in [1.9.0](https://github.com/themetalfleece/neogma/releases/tag/v1.9.0).
