### ISSUE TITLE
Error // old parameter syntax `{param}` is no longer supported

### ISSUE THREAD

**Issue by litewarp** [themetalfleece/neogma#22]
I am getting the following error using the 'create' function on queryRunner: 

```
Neo4jError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead
```

This is [the offending syntax](https://github.com/themetalfleece/neogma/blob/f73a96450eaa876e86643d21495c414f03ebe168/src/Queries/QueryRunner/QueryRunner.ts#L106). 

Not sure when things switched over, but it now errs.

<img width="1620" alt="Screen Shot 2021-06-01 at 12 36 13 AM" src="https://user-images.githubusercontent.com/1900476/120286423-14261600-c273-11eb-922e-891e13fe793d.png">

**Comment by themetalfleece** [comment]
Thanks for reporting this bug. I'll get to it soon!

**Comment by themetalfleece** [comment]
Deployed in [1.9.0](https://github.com/themetalfleece/neogma/releases/tag/v1.9.0), this should no longer be an issue.
