### ISSUE TITLE
findRelationship alias Type 'string' is not assignable to type 'never'

### ISSUE THREAD

**Issue by tejo-ak** [themetalfleece/neogma#26]
I am implementing the brand new `findRelationship` feature and got `Type 'string' is not assignable to type 'never'` error for the `alias` property.

The type seems to be different from the `alias` property of, for example, the `modelInstance`.`relateTo`, which is the `keyof ModelRelatedNodesI`

Thanks.

**Comment by themetalfleece** [comment]
This is weird, the parameter of `Alias` is the same in both `relateTo` and `findRelationships`. I also cannot reproduce it.
Would you mind sharing some code which reproduces this issue (including the Model definition)?
Thanks

**Comment by tejo-ak** [comment]
I'have done a fresh npm install and the problem gone.
