### ISSUE TITLE
delete relationShip

### ISSUE THREAD

**Issue by tejo-ak** [themetalfleece/neogma#27]
Hello,
Now that you have a set of APIs for relationships, it become a necessity to add another: `deleteRelationship`, which, doesn't seems to be there now.

Thanks for considering.

Regards,

**Comment by Ansis100** [comment]
Does anyone have any workaround for now? Do we need to use query builder for removing relationships?

**Comment by themetalfleece** [comment]
It's finally here!
Deployed in version [1.11.0](https://github.com/themetalfleece/neogma/releases/tag/v1.11.0).
I've also added various workflows to allow easier contribution to neogma, which are all described in the releate notes.
