### ISSUE TITLE
Check if relationship between two nodes exists: error with findRelationships

### ISSUE THREAD

**Issue by ChristopherCODE14** [themetalfleece/neogma#30]
Good morning, 

I try to find a relationship between two given nodes. 
In fact, I already tried to use the both methods, described in the documentation. However, I get the following error message: 

> product.findRelationships is not a function

Here is my code:

`public static async findRelationshipBetweenTwoGivenNodes(id1: string, id2: string, alias: string, res: any, next: any):Promise<any> {
        try {
            let product: any = ProductService.findProductById(id1, res);
            const relationships:any = product.findRelationships({
                alias: alias,
                where: {
                    target: {
                        id: id2
                    },
                },
                limit: 1
            });

            return relationships;
        } catch (err) {
            return res.status(401).send(err.message);
        }
    }`

Do you know what is wrong?

**Comment by themetalfleece** [comment]
Good morning Christpher
1) Are you using the latest neogma version?
2) Are you sure that `product` is a propert Instance? How does it get returned in `findProductById`?

**Comment by ChristopherCODE14** [comment]
Good afternoon Jason, 

I just updated neogma and it works now!
