### ISSUE TITLE
Problem: Creating nodes with bidirectional relationships

### ISSUE THREAD

**Issue by nberthier** [themetalfleece/neogma#34]
Hi! Currently trying to develop a backend with neogma. Enjoying it so far but I bumped into a problem with relationships.

### Context

So let's say I have two types of nodes : 
- User
- Product

The relationship between the two is likeso : 
- User --[ORDERS]--> Product
- Product --[ORDERED_BY]--> User

So that we can find nodes in both directions (all products ordered by a specific user / all users who have ordered a specific product).

### Problem

I created the same relationships in both models (one with direction 'in' and one with direction 'out'), but when I want to create a new relationship (order) from user to product, I get the error "Cannot read property 'getLabel' of undefined" which comes from the ModelOps file in the function relateTo (line 610).  
But if I don't create the relationship in the Product model, I can create the relationship without any problem, but I can't query the users who ordered a specific product.  
I think the issue comes from the "model" property of the relationship in the ModelFactory.  

Am i doing things wrong or maybe the bidirectional relations are not possible with neogma ?

Thanks for your help !

**Comment by themetalfleece** [comment]
Added documentation here: https://themetalfleece.github.io/neogma-docs/docs/Models/Defining-a-Model#declaring-bidirectional-relationships
