### ISSUE TITLE
One to Many

### ISSUE THREAD

**Issue by SynergyEvolved** [themetalfleece/neogma#35]
Hi there!

I have just started to try to work with Neogma and I am trying to create a 1 to Many relationship.

I have a Business with many Trading Entities like such:  Business & { TradingEntities: Trading_Entity[] }

I believe I should be using createMany for this, as it looks much the same as the User & many Orders example from the Readme.  

My problem is that the example doesn't show what the Orders Model looks like and when I search neogma-doc for createMany I get no results.

Could I please get a working example of a One-to-Many create?  

Thanks

Paul

**Comment by themetalfleece** [comment]
Hey Paul,

The search function in the docs doesn't work as expected, I need to fix it.

For your issue:
If the "Business" entry already in the database and you want to create many TradingEntities (`TradingEntities.createMany`), you need to do something like [this](https://themetalfleece.github.io/neogma-docs/docs/Models/Creating-Nodes-and-Relationships#creating-many-nodes), and each entry needs to refer to `Business` via a `where` (like in the code [here](https://themetalfleece.github.io/neogma-docs/docs/Models/Creating-Nodes-and-Relationships#creating-a-single-node-of-the-model-while-relating-it-with-other-nodes)).

Please let me know if this of any help.

**Comment by SynergyEvolved** [comment]
That helped a lot - thanks!
