### ISSUE TITLE
Return information indicating whether update of relationship was successfull

### ISSUE THREAD

**Issue by JonasHiltl** [themetalfleece/neogma#37]
When updating a relationship with the `updateRelationship` method either through an instance or the model itself it is not possible to know if the update was successfull or if for example the target was icorrect.
I tried updating the relationship of a user with the function below and I could not find a value on the result object that indicated if the update was successfull. 
For me the `records` array in the result was always an empty list even when the update was successfull. The `updateStatistics` also did not change between an update that changed the relationship and an update that did not change anything. Is it possible to return the number of updates that got executed so that we can decide if the update was successfull?
```typescript
const result = await User.updateRelationship(
  { accepted: false },
  {
    alias: "Friend",
    where: {
      source: {
        id: req.user?.id.trim()!,
      },
      target: {
        id: req.params.id.trim(),
      },
      relationship: {
        accepted: true,
      },
    },
  }
);
```

**Comment by themetalfleece** [comment]
`updateRelationship` returns the query result as is (from the neo4j driver), so there is nothing that Neogma can generate that isn't already there.

Does the following have any useful information?
```ts
console.log(result.summary.counters.updates());
```

**Comment by JonasHiltl** [comment]
`propertiesSet` returns the number of properties that got updated. I will use that to determine if the update was successfull. Thanks a lot
