### ISSUE TITLE
[Question] For pagination purposes, is it possible to have total count as part of same query?

### ISSUE THREAD

**Issue by jotamorais** [themetalfleece/neogma#42]
Hi everyone,

I know that total count/quantity with raw cypher queries is not the easiest/prettiest thing in Neo4j. I was wondering if there's a way to get the total count in a single "transaction" instead of making 2 calls to the database?

Reference: https://community.neo4j.com/t/get-count-before-limit/15378/7

Thank you!

**Comment by themetalfleece** [comment]
Hey there,

There is no way in Neogma to do this, and the answer in your link can be easily created using Neogma's `QueryBuilder`!
Adding it as a Model static could be tricky if any relationship is included, but pretty straightforward when only one Model is used (like in the example).
