### ISSUE TITLE
Bug: Infinity max hops improperly working

### ISSUE THREAD

**Issue by tomek7667** [themetalfleece/neogma#72]
```
            /* --> (optional) minimum hops for a variable length relationship */
            minHops: 1,
            /* --> (optional) maximum hops for a variable length relationship. The value Infinity can be used for no limit on the max hops */
            maxHops: 1,
```

The comment stating that value Infinity will be no limit for the recursion is not accurate. When entered `9999999` working perfectly fine, when entered `Infinity` works like for a 1 hop.

**Comment by themetalfleece** [comment]
Hello, using `Infinity` generates a `[*]` relationship which matches [1 or more iterations](https://neo4j.com/docs/cypher-manual/current/patterns/reference/#variable-length-relationships-rules).
So, is `[*]` used in the generated cypher but doesn't work as expected?

**Comment by tomek7667** [comment]
I see, I think that I misunderstood the feature, sorry for the trouble

**Comment by themetalfleece** [comment]
No worries. In the meantime I found out a bug when only `minHops` is passed, I'll create a fix soon.
