### ISSUE TITLE
[Question] Is there a way to delete a node and all its relationships recursively, including the related nodes?

### ISSUE THREAD

**Issue by pedromtcosta** [themetalfleece/neogma#82]
Does neogma provide a way to delete a node together with all its relationships and related nodes? Or do I have to resort to using Cypher for that?

**Comment by themetalfleece** [comment]
Hey! I'm afraid you'll have to resort to using Cypher (or via the QueryBuilder) for that.
I had started implementing it, but it seemed a bit "dangerous" to have neogma delete all related nodes found via a given condition, and I decided to not go through with it.
