### ISSUE TITLE
Returning nodes with a large amount of relationships?

### ISSUE THREAD

**Issue by exoup** [themetalfleece/neogma#85]
Not an issue but a question.

I currently am using an OGM called Neode but am running into memory limit issues when it queries a node with a large amount of relationships (1500 or so).

How well does Neogma handle large lookups like this?

In my case, the node should return fully hydrated so I can access the nodes it has a relationship with.
Is this a Neogma use case?

Thanks

**Comment by themetalfleece** [comment]
Hey there,

I haven't had a use case to test the memory usage like this.
However:

1. If you use the [model statics](https://themetalfleece.github.io/neogma/docs/Models/Finding-Nodes-And-Relationships), an Instance of the class of each related Node will be created, which could increase the memory usage.
2. However, if you use the [QueryBuilder](https://themetalfleece.github.io/neogma/docs/QueryBuilder/Overview), it will use the same memory as you would get from the default neo4j driver.

**Comment by exoup** [comment]
In some quick testing, Neogma seems to handle my use case better than Neode. I'll see about adapting my code base.

One more question, if you don't mind: The docs mention when creating models to define all of the potential relationships for that model.

I presume we only need to define the relationship in one model going one way and not on both models.
How could I handle a relationship between the same type of nodes, like User-[:KNOWS]->User going both ways? 
Would I just create an alias TO and FROM?

Thanks!

**Comment by themetalfleece** [comment]
That's good to hear :)

> I presume we only need to define the relationship in one model going one way and not on both models.

You basically have to define it on both models, but you can use the [reverseRelationshipConfiguration](https://themetalfleece.github.io/neogma/docs/Models/Defining-a-Model#declaring-bidirectional-relationships) static so you won't have to repeat the definition.

> How could I handle a relationship between the same type of nodes, like User-[:KNOWS]->User going both ways?

Yeah, you could do that so you're able to query it both ways :) Make sure to use the ['self'](https://themetalfleece.github.io/neogma/docs/Models/Defining-a-Model#relating-a-model-to-itself) value when relating to the same model.

Let me know if anything else needs clearing up :)

**Comment by exoup** [comment]
Thank you for the help! I missed that part in the documentation during my first read through.
I think I've got everything under control for now so I'll close out this question.

I'm looking forward to using Neogma more. It's pretty nice!
