### ISSUE TITLE
[Feature Request] Add support for temp/test dbs with @neo4j-labs/temp-dbs

### ISSUE THREAD

**Issue by AndySakov** [themetalfleece/neogma#88]
Testing with neo4j as we all know leaves much to be desired but it would be nice if we could spawn test dbs so that integration tests that include the database would be possible. For reference, [this lib](https://github.com/neo4j-contrib/neo4j-temp-db) makes it possible already but the design choices made by the devs of the lib make it hard to integrate the lib with neogma without reaching into neogma source and tweaking some things.

**Comment by themetalfleece** [comment]
Thanks for your contribution! Released at [v1.13.0](https://github.com/themetalfleece/neogma/releases/tag/v1.13.0)
