### ISSUE TITLE
Limit & Skip issue

### ISSUE THREAD

**Issue by BOISSARD** [themetalfleece/neogma#91]
Hello 

When using LIMIT and SKIP in the same query (findMany for instance) it gives me an issue because it generates something like :
```
MATCH (Node) RETURN Node ASC LIMIT $limit SKIP $skip
```
But it should be like 
```
MATCH (Node) RETURN Node ASC SKIP $skip LIMIT $limit 
```
to work properly.

**SKIP should appears before  LIMIT**

Thank you for your incredible work

**Comment by BOISSARD** [comment]
My bad I wasn't up to date

**Comment by themetalfleece** [comment]
Hey, thanks for your kind words :) Indeed it was an issue (#43) that was fixed on version [v.1.10.3](https://github.com/themetalfleece/neogma/releases/tag/v1.10.3)
